version: "3.9"
services:
  twitter-sentiment:
    build: .
    command: bash -c "python src/train.py --exp_name=tfidf_logreg
      && python src/test.py --db-user=${POSTGRES_USER} --db-password=${POSTGRES_PASSWORD} --db-name=${POSTGRES_DBNAME}
      && coverage run src/unit_tests/test_preprocess.py
      && coverage run -a src/unit_tests/test_training.py
      && coverage report -m"
    ports:
      - "8000:8000"
    image: danielto1404/ml-pipe-twitter-sentiment:latest
    links:
      - "postgres:database"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=password # https://github.com/aws/aws-mwaa-local-runner/issues/237#issuecomment-1510983321
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DBNAME}" ]
      timeout: 20s
      retries: 5